### ISSUE TITLE
Blank page on testing branch 

### ISSUE THREAD

**Issue by anmol26s** [YunoHost-Apps/wekan_ynh#19] opened 2018-06-16 14:50 UTC
Hi
I see blank page when the app is installed from the testing branch. I am on Debian Jessie.

**Comment by alexAubin** [comment] 2018-06-16 14:51
The app is broken because the archive disappeared upstream again :/ We need to discuss what to do (c.. #18 )

**Comment by anmol26s** [comment] 2018-06-16 14:56
But testing branch has version1.02 which is there still :https://releases.wekan.team/wekan-1.02.tar.gz

**Comment by 4abhinavjain** [comment] 2018-07-07 08:29
Any updates on  it? I just installed it and it is giving an empty page to me as well.

**Comment by alexAubin** [comment] 2018-10-22 20:38
Hellow,

if you want to regive a try, https://github.com/YunoHost-Apps/wekan_ynh/pull/23 have been merged and should make the app compatible with stretch.

Closing the issue until there's more feedback or it can be reproduced

**Closed by alexAubin** 2018-10-22 20:38 UTC
